### ISSUE TITLE
❌ An error occurred while parsing the JSON obtained from the Sublist3r API. Error description: reqwest::Error { kind: Decode, source: Error("invalid type: null, expected a sequence", line: 1, column: 4) }.

### ISSUE THREAD

**Issue by rapradab** [Findomain/Findomain#120]
❌ An error occurred while parsing the JSON obtained from the Sublist3r API. Error description: reqwest::Error { kind: Decode, source: Error("invalid type: null, expected a sequence", line: 1, column: 4) }.

**Comment by Edu4rdSHL** [comment]
Hello, this happens when no subdomains are found in that source. It's an API problem that returns a 200 HTTP code still when nothing is found there and then the tool tries to deserialize the JSON body. It will not cause any problem.

**Comment by kpcyrd** [comment]
I haven't checked, but I think this could be fixed here:
https://github.com/Findomain/Findomain/blob/4692d57e246fc7b5fb904694ec89cc4d2aafdb29/src/sources.rs#L420
by changing it to `Option<HashSet<String>>`

**Comment by Edu4rdSHL** [comment]
We have several ways to fix ~~hide~~ it, but again, we check if the request is successful [here](https://github.com/Findomain/Findomain/blob/4692d57e246fc7b5fb904694ec89cc4d2aafdb29/src/sources.rs#L196), so in this case the problem is caused by the API sending a wrong response code.
