### ISSUE TITLE
New update is giving me errors 

### ISSUE THREAD

**Issue by MR-pentestGuy** [Findomain/Findomain#123]
error[E0658]: non-builtin inner attributes are unstable
--> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-parser-0.10.1/src/generated.rs:4:1
error: could not compile `semver-parser`.

**Comment by Edu4rdSHL** [comment]
Hello, what's the output of `rustc -V`?

**Comment by MR-pentestGuy** [comment]
this what i am getting 
error[E0658]: non-builtin inner attributes are unstable
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-parser-0.10.1/src/generated.rs:4:1
  |
4 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information

   Compiling atty v0.2.14
   Compiling mio v0.7.6
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `semver-parser`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed


i am using version 1.43.0

**Comment by MR-pentestGuy** [comment]
i have updated rust now its fine thank u
