### ISSUE TITLE
Database schema not updated properly

### ISSUE THREAD

**Issue by teslatheg0d** [Findomain/Findomain#127]
Findomain 3.0.0 
`
findomain -m -c findomain.config.toml -t domain.com
`
doing everything right but 
writing output to database is not working 

But reading from database is working 
`
findomain -c findomain.config.toml --query-database -t domainother.com
`

My config file `findomain.config.toml` contains 
`
postgres_connection = "postgresql://postgres:password@localhost:5432/findomaindb" 
`

Can you please investigate that....

**Comment by Edu4rdSHL** [comment]
Hello, to use the `-m` flag you need to set at least one webhook. If you just want to retrieve subdomains and then import to database, use the `--no-monitor` flag.

I'm not sure if that's what you're actually trying to do.

**Comment by teslatheg0d** [comment]
I have a one webhook.
`
slack_webhook = "https://hooks.slack.com/services/XXXXX/XXXXXXXXXXXXX" 
`

**Comment by teslatheg0d** [comment]
webhook is working properly 

but that saving output to database is not...

**Comment by Edu4rdSHL** [comment]
What do you actually mean with "saving output do database"? Means saving the subdomains to the database?

**Comment by teslatheg0d** [comment]
yes

**Comment by Edu4rdSHL** [comment]
I can not reproduce the issue: https://asciinema.org/a/5GeyJ62rvZgVscmHSjMlajmgJ, can you provide more details? The database `findomaindb` exists? You need to create the database first.

**Comment by teslatheg0d** [comment]
I have created the database... before findomain 3.0.0
all was working fine

after updating to findomain 3.0.0
I wasn't able to save Subdomains to the database..

**Comment by Edu4rdSHL** [comment]
What's your PostgreSQL version? `psql -V`

**Comment by teslatheg0d** [comment]
psql (PostgreSQL) 13.1 (Debian 13.1-1+b1)

**Comment by teslatheg0d** [comment]
and one thing more that 

database doesn't have other columns 
![image](https://user-images.githubusercontent.com/61558155/105654668-81502600-5ee4-11eb-88e5-7fd26bf0b262.png)

**Comment by Edu4rdSHL** [comment]
Yeah, that's what I was suspecting, that should be handled by https://github.com/Findomain/Findomain/blob/cfea557b420e9098cd4ff0532f477248dbbd3304/src/database.rs#L30-L39

but as it was an independent development I didn't have into account the old database schema that the free version was using. 

You have two options: create a new database and work with that, or wait a few minutes while I release a fix.

**Comment by teslatheg0d** [comment]
okay

**Comment by Edu4rdSHL** [comment]
New release have been made. Thank you for reporting the issue. https://github.com/Findomain/Findomain/releases/tag/3.0.1

**Comment by teslatheg0d** [comment]
My pleasure.... 👍
