### ISSUE TITLE
CTSearch returns a 403

### ISSUE THREAD

**Issue by jamesnixon197** [Findomain/Findomain#132]
CTSearch has stopped working, returns a 403 on all requests now.

Example:
https://ctsearch.entrust.com/api/v1/certificates?fields=subjectDN&domain=google.com&includeExpired=true&exactMatch=false&limit=5000

**Comment by Edu4rdSHL** [comment]
Hello, @jamesnixon197 thank you for the report. Do you know if they have changed the API or if they have shutdown the service definitely? Anyways, that isn't a problem for Findomain and you will not suffer any kind of problem.

**Comment by jamesnixon197** [comment]
Yeah, fair enough. Was just notifying you incase it was worth removing / excluding the service by default. It does look like it's been taken down, can't find anything about an API key that needs to be used.

**Comment by Edu4rdSHL** [comment]
Thank you, I have send an email to Ctsearch to confirm.

**Comment by Edu4rdSHL** [comment]
Well, they didn't give any useful information but looks like it was removed. I will remove that source from our list.

**Comment by shadowzoom** [comment]
> Well, they didn't give any useful information but looks like it was removed. I will remove that source from our list.

I found a working link https://ui.ctsearch.entrust.com/ui/ctsearchui

**Comment by Edu4rdSHL** [comment]
I personally haven't interest in working with HTML right now, they don't offer a proper API for querying but instead wants to force you to use their "UI".
