### ISSUE TITLE
Add API key support for certspotter source

### ISSUE THREAD

**Issue by bugbaba** [Findomain/Findomain#134]
Hi Eduard,

Currently, findomain supports certspotter, But it's sending unauthenticated request due to which hits the daily rate limit too soon. It would be better to support API key which will help with few more requests even with a free account.

https://sslmate.com/certspotter/api/pricing

--
Regards,
@bugbaba

**Comment by Edu4rdSHL** [comment]
Hello, it has been implemented. You can use the `certspotter_token` variable inside your config file.

**Comment by bugbaba** [comment]
Thanks :)
