### ISSUE TITLE
Error when returning the browser instance for screenshots

### ISSUE THREAD

**Issue by mzfr** [Findomain/Findomain#136]
so I am seeing this error when I run `findomain` and I am not sure why this might be happening:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: HttpError(Io(Custom { kind: UnexpectedEof, error: "end of stream before headers finished" }))', src/utils.rs:23:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: HttpError(Io(Custom { kind: UnexpectedEof, error: "end of stream before headers finished" }))', src/utils.rs:23:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionClosed', src/utils.rs:23:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout', src/utils.rs:23:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I am using **Ubuntu 20.04**

**Comment by Edu4rdSHL** [comment]
Hello, please can you tell me the following information:

1) The exact findomain command that you're using.
2) The output for `ulimit -n` and `ulimit -a`
3) The output for `uname-a`

**Comment by mzfr** [comment]
- The findomain command is:
```
 findomain -t "$fixed_domain" --import-subdomains "$total_file" -o -c /var/findomain/config.yml -m -q --http-status -i --pscan --iport 1 --lport 65535 -s screenshots --mtimeout --threads 10 --unlock
```

- `ulimit -n`  -> 1024
- `ulimit -a`
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 3869
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 3869
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
- `Linux ip-MY-IP-HERE 5.4.0-1037-aws #39-Ubuntu`

**Comment by Edu4rdSHL** [comment]
Can you tell me what's inside your config.yml? Obviously you can replace API keys and any confidential information.

**Comment by kpcyrd** [comment]
It seems the unwrap happens in this line:
https://github.com/Findomain/Findomain/blob/d375250010d3e5bc7bdea5692d6500de83905e33/src/utils.rs#L23
The errors sound like they're due to RST packets, which shouldn't cause an application panic, so this should return a `Result<Browser>` instead. :) I'm not sure what's being loaded in that function though since that function doesn't seem to use any urls.

**Comment by mzfr** [comment]
I am not sure if this is like some code issue or something to do with the machine load. 

I ran the following command and got the same error in like 3 seconds and then I re-ran the same command and it worked(gave no error):

```
findomain -t "google.com" --import-subdomains total_file -o -c /var/findomain/config.yml -m -q --http-status -i --pscan --iport 1 --lport 65535 -s screenshots --mtimeout --threads 10
```

on the first try I got: 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout', src/utils.rs:23:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

And then on the second trial it just worked fine.

**Comment by Edu4rdSHL** [comment]
> * The findomain command is:
> 
> ```
>  findomain -t "$fixed_domain" --import-subdomains "$total_file" -o -c /var/findomain/config.yml -m -q --http-status -i --pscan --iport 1 --lport 65535 -s screenshots --mtimeout --threads 10 --unlock
> ```
> 
> * `ulimit -n`  -> 1024
> * `ulimit -a`
> 
> ```
> core file size          (blocks, -c) 0
> data seg size           (kbytes, -d) unlimited
> scheduling priority             (-e) 0
> file size               (blocks, -f) unlimited
> pending signals                 (-i) 3869
> max locked memory       (kbytes, -l) 65536
> max memory size         (kbytes, -m) unlimited
> open files                      (-n) 1024
> pipe size            (512 bytes, -p) 8
> POSIX message queues     (bytes, -q) 819200
> real-time priority              (-r) 0
> stack size              (kbytes, -s) 8192
> cpu time               (seconds, -t) unlimited
> max user processes              (-u) 3869
> virtual memory          (kbytes, -v) unlimited
> file locks                      (-x) unlimited
> ```
> 
> * `Linux ip-MY-IP-HERE 5.4.0-1037-aws #39-Ubuntu`

@mzfr  the maximum number of user processes and open files is too low, you need to increase them. In my case the values are `102400` for both. You can achieve it  modifying your `/etc/security/limits.conf` file and appending the following lines:

```
* soft nofile 102400
* hard nofile 102400
* soft nproc 102400
* hard nproc 102400
```
reboot the machine and once you've logged in again check the limits with `ulimit -n` and `ulimit -u`, then try again.

> It seems the unwrap happens in this line:
> https://github.com/Findomain/Findomain/blob/d375250010d3e5bc7bdea5692d6500de83905e33/src/utils.rs#L23
> 
> 
> The errors sound like they're due to RST packets, which shouldn't cause an application panic, so this should return a `Result<Browser>` instead. :) I'm not sure what's being loaded in that function though since that function doesn't seem to use any urls.

@kpcyrd in this case we need to finish the application execution if the `--screenshots` option was passed to Findomain but the system doesn't return the browser instance that we need and as a consequence we cannot take screenshots, I agree that the error message should be more clear but it's something that "will not fails".

> I am not sure if this is like some code issue or something to do with the machine load.

@mzfr it's because the machine load, we are getting a `Timeout` when Findomain tries to create a new browser instance to take the screenshots:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout', src/utils.rs:23:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I have run the same command and haven't had errors here even using `--threads 50`, what are the specs of your machine? Also, it's possible that you're suffering from [Chromium hanged instances](https://twitter.com/FindomainApp/status/1363900240512897025) wasting your resources, so follow the instructions in https://github.com/Findomain/Findomain/tree/master/Utilities#kill-chromiumchrome-hanged-instances as well.

Finally, what are your VPS specs in terms of memory/CPU?

**Comment by mzfr** [comment]
I was not aware about the `ulimit` thing do I'll make sure to increase that 

> @mzfr it's because the machine load, we are getting a Timeout when Findomain tries to create a new browser instance to take the screenshots:

I dont think it's because of the load. I am saying this because when i ran those command I was keeping an eye on the usage and load never went above 200-300 mb of RAM and about 14-15% of CPU usage. I have 2 GB of RAM and 2 core CPU(10 USD/per month droplet on digital ocean) 

> Also, it's possible that you're suffering from Chromium hanged instances wasting your resources, so follow the instructions in https://github.com/Findomain/Findomain/tree/master/Utilities#kill-chromiumchrome-hanged-instances as well.

Oh yeah maybe this could be one of the reasons I'll try this solution and see if things get fixed

**Comment by Edu4rdSHL** [comment]
I hope it helps, additionally chromium in latest Ubuntu machines is getting installed from snap causing it to act strange and fail (snap sucks). If none of the above solutions works for you, then uninstall chromium and install chrome:

```
apt --purge remove chromium*
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
apt install ./google-chrome-stable_current_amd64.deb
```
and run Findomain again, you shouldn't have problems.

**Comment by Edu4rdSHL** [comment]
I have added some workarounds in https://github.com/Findomain/Findomain/commit/533603da3b7eac8367cba4a7c56ebc0542893dc8 and https://github.com/Findomain/Findomain/commit/0b71a164752c206be891bed574d74c9305ee836a

@mzfr please let me know if the steps posted in the previous comments fixed your issue, also try the [new 3.1.0 release](https://github.com/Findomain/Findomain/releases/tag/3.1.0) that updates several dependencies including the Rust chromium library that we use.

**Comment by 0xAgentSteal** [comment]
> I have added some workarounds in [533603d](https://github.com/Findomain/Findomain/commit/533603da3b7eac8367cba4a7c56ebc0542893dc8) and [0b71a16](https://github.com/Findomain/Findomain/commit/0b71a164752c206be891bed574d74c9305ee836a)
> 
> @mzfr please let me know if the steps posted in the previous comments fixed your issue, also try the [new 3.1.0 release](https://github.com/Findomain/Findomain/releases/tag/3.1.0) that updates several dependencies including the Rust chromium library that we use.

I've downloaded the latest release and I am having the same problem as @mzfr .
Findomain works if I set variables in .bashrc but does not work with my config specified:
                                      
postgres_connection: "postgresql://user:pass@host:5432/dbname
virustotal_token: "token"
securitytrails_token: "token"
spyse_token: "token"
discord_webhook: "https://discord.com/api/webhooks/hook"
user_agent: "useragentstring"
threads: "100"
rate_limit: "7"
dbpush_if_timeout: "Enable --mtimeout flag"

Do you think there's a problem with the config file?

Regards,
@0xAgentSteal

**Comment by Edu4rdSHL** [comment]
Hello, @0xAgentSteal, your problem is different from the @mzfr one, it isn't related to Chrome/Chromium in the first place, open a separate issue for this but be specific: what format are you using for the config file, what's the error message that you're getting (copy and paste the error message), what's the output of `findomain -V` and what's the content of your config file.

**Comment by mzfr** [comment]
@Edu4rdSHL Yeah so now things seems to work. I didn't setup any cron for chrome, I just used the new binary.

I even got the new message saying `Chromium/Chrome is correctly installed, performing enumeration!`

Great work!! 😄
