### ISSUE TITLE
 Add API key support for C99.nl source

### ISSUE THREAD

**Issue by 0xAgentSteal** [Findomain/Findomain#138]
Hi Eduard,

Currently, Findomain supports C99 source (saw it in the Readme), but using the variable findomain_c99_token="API-KEY" does not work, unfortunately. The source is not being loaded.
Do you think it's possible to fix this?
Thanks!

--
Regards,
@0xAgentSteal

**Comment by Edu4rdSHL** [comment]
It's because the variable needs to be called `findomain_c99_api_key`.
