### ISSUE TITLE
Add support for multiple UserAgens in the configuratios file.

### ISSUE THREAD

**Issue by ZeroDot1** [Findomain/Findomain#140]
It is better if Findomain can change the UserAgent automatically between the requests if several UserAgents are entered in the configuration file.

You can find different up-to-date UserAgents e.g. on the following page.
https://www.whatismybrowser.com/guides/the-latest-user-agent/

**Comment by Edu4rdSHL** [comment]
Hello, it has been implemented. You can use the `--ua` option in the command line or the `user_agents_file` valiable in the config file to point to your user agents file.

**Comment by ZeroDot1** [comment]
Many thanks, I will test it later directly.
