### ISSUE TITLE
Add support for multiple APIKeys in the configuratios file

### ISSUE THREAD

**Issue by ZeroDot1** [Findomain/Findomain#141]
In some situations it is important to be able to use multiple API keys for a service.
It should also be used the API keys randomly always, if at least 2 API keys for a service are in the configuration file.
A random use of multiple API keys ensures that you are not blocked in case of a large number of requests.

**Comment by Edu4rdSHL** [comment]
Hello, thank you for the proposal, it's already implemented in the plus version, I will backport the feature at some point.

**Comment by ZeroDot1** [comment]
That sounds very good, thank you very much.

**Comment by Edu4rdSHL** [comment]
The feature has been backported, you can add multiple api keys in the config file separating them with comma, for example:

```
spyse_token = "api1,api2,api3,api3,api4"
securitytrails_token = "api1,api2,api3,api3,api4,api5,api6,api7"
```
and so on.

**Comment by ZeroDot1** [comment]
Hi @Edu4rdSHL,

Thank you for implementing the feature so quickly.
