### ISSUE TITLE
Add a new switch for random requests.

### ISSUE THREAD

**Issue by ZeroDot1** [Findomain/Findomain#142]
For example, when checking a list of domains for subdomains, in some situations it makes a lot of sense to run the queries randomly instead of line by line.
This function is especially important if you have very large lists and they are sorted e.g. alphabetically.

I have noticed that if you check too many domains in alphabetical order, it can happen that you are blocked by the services or get less results.

My suggestion for the switch `-fr` (FR Means file random read)

**Comment by Edu4rdSHL** [comment]
Hi, please can you build from source and let me know if it's what you want? To use it you need to use the `--randomize` flag in the command line or `randomize = "true"` in the config file.

Thanks a lot for then idea.

**Comment by ZeroDot1** [comment]
Hi @Edu4rdSHL,

Thank you for implementing the feature so quickly.
It works very well, and prevents users from being blocked by the services.
