### ISSUE TITLE
Unfriendly quit if targets file is empty or all targets are invalid

### ISSUE THREAD

**Issue by blackcodersec** [Findomain/Findomain#143]
What it the problem? 

![image](https://user-images.githubusercontent.com/72689232/117573540-4d4aea80-b0fa-11eb-9d86-561aded49074.png)

**Comment by Edu4rdSHL** [comment]
Hello, please check the content of your `live` file and make sure that it doesn't contain weird characters or something. I have tried to reproduce the issue without success. Also make sure that you're using the latest Findomain version which is `4.1.1`, use `findomain -V` to check.

**Comment by kpcyrd** [comment]
I think this happens if `live` is empty, or all targets got filtered by `logic::validate_target`, so `file_targets` is empty:
```rust
let last_target = file_targets.last().unwrap().to_string();
```
The unwrap in that line assumes there's always at least one target, which isn't true (as proven by the crash), the `is_last_target` code can be rewritten though so the unwrap is not necessary anymore:
```rust
let mut file_targets = if !args.files.is_empty() {
    return_file_targets(args, args.files.clone())
} else {
    utils::read_stdin()
};

file_targets.retain(|target| !target.is_empty() && logic::validate_target(target));

if args.randomize {
    let file_targets_hashet: HashSet<String> = HashSet::from_iter(file_targets.clone());
    file_targets = file_targets_hashet.into_iter().collect()
}

let mut iter = file_targets.into_iter().peekable();
while let Some(domain) = iter.next() {
    if iter.peek().is_none() {
        args.is_last_target = true
    }   
    args.target = domain;
    args.file_name = if file_name.is_empty() && !args.with_ip {
        format!("{}.txt", &args.target)
    } else if file_name.is_empty() && args.with_ip {
        format!("{}-ip.txt", &args.target)
    } else {
        file_name.to_string()
    };  
    crate::get_subdomains(args)?
}
```

**Comment by Edu4rdSHL** [comment]
I was thinking in doing something like:

```rust
        let last_target = if file_targets.is_empty() {
            eprintln!("Could not find any valid target, please check that the file is not empty and the targets are valid.");
            std::process::exit(1)
        } else {
            file_targets.last().unwrap().to_string()
        }
```

What do you think?

**Comment by blackcodersec** [comment]
> Hello, please check the content of your `live` file and make sure that it doesn't contain weird characters or something. I have tried to reproduce the issue without success. Also make sure that you're using the latest Findomain version which is `4.1.1`, use `findomain -V` to check.

Ohh, I sorry to say, "live" files there are including http and https format line. That's why maybe I got this error. and I used 4.1.1 version. Thanks

**Comment by Edu4rdSHL** [comment]
> > Hello, please check the content of your `live` file and make sure that it doesn't contain weird characters or something. I have tried to reproduce the issue without success. Also make sure that you're using the latest Findomain version which is `4.1.1`, use `findomain -V` to check.
> 
> Ohh, I sorry to say, "live" files there are including http and https format line. That's why maybe I got this error. and I used 4.1.1 version. Thanks

Hey @blackcodersec, yes, that will cause the error as the targets should be only in the `domain.tld` format. Anyways, I will add a couple of lines of code to make this error more friendly and told the user what happened.

Thank you for reporting.
