### ISSUE TITLE
API Configuration

### ISSUE THREAD

**Issue by mohakawtar** [Findomain/Findomain#146]
Hi
I cant't  set any API key .
version 4.3.
OS: Windows and Kali.
thanks

**Comment by Edu4rdSHL** [comment]
Read [the documentation](https://github.com/Findomain/Findomain/blob/master/docs/INSTALLATION.md#access-tokens-configuration).

**Comment by mohakawtar** [comment]
![image](https://user-images.githubusercontent.com/6909501/122202887-c37f0180-ce9d-11eb-95f2-728998f4e989.png)

**Comment by Edu4rdSHL** [comment]
`-(options)` needs to be replaced by valid findomain options. See `findomain --help`, also read https://findomain.app/the-real-power-of-findomain/

**Comment by mohakawtar** [comment]
Thanks Edu4rdSHL.
