### ISSUE TITLE
Error while compiling Findomain

### ISSUE THREAD

**Issue by Karan4580** [Findomain/Findomain#154]
cargo build --release
   Compiling findomain v5.0.0 (/home/karan/tools/findomain)
error: argument for `--edition` must be one of: 2015|2018. (instead was `2021`)
![Screenshot from 2021-11-08 16-40-55](https://user-images.githubusercontent.com/90746854/140732059-9d61395c-9d9d-4ba4-a6f9-82b41b503941.png)
error: could not compile `findomain`

**Comment by Edu4rdSHL** [comment]
Hello, please update Rust to the 1.56 version at least.

**Comment by Karan4580** [comment]
> Hello, please update Rust to the 1.56 version at least.

Thank You 😊
