### ISSUE TITLE
Add the possibility to save user defined paths for Amass and Subfinder in the configuration file.

### ISSUE THREAD

**Issue by ZeroDot1** [Findomain/Findomain#155]
This is important if you have created subfnder from the sources and want to test it before using it in production.

Configuration entry example:

`external-subdomains = "Your path to Amass,Your path to Subfinder"`

**Comment by ZeroDot1** [comment]
And additionally it would be good if you could use the configuration files for Amass and Subfinder.

**Comment by Edu4rdSHL** [comment]
You just need to put the binaries in the PATH variable, we don't harcode any path but just launch them directly from the system's PATH, that will not change.

Regarding to the configuration files, just place them in the required places, ~/.config/amass for Amass and ~/. config/subfinder for Subfinder.
