### ISSUE TITLE
[ screenshot option] Chrome/Chromium.exe instances does not terminate after screenshot is taken

### ISSUE THREAD

**Issue by MaxArthurQueen** [Findomain/Findomain#156]
Hi! Thanks for your great work guys. I just wander if it's only in my case ? I'm windows 7

**Comment by Edu4rdSHL** [comment]
Hello, @MaxArthurQueen, thanks for the report, can you please explain a bit more what the problem is or what do you mean exactly?

**Comment by MaxArthurQueen** [comment]
Shure!
i sended it a list of 3000 websites to check
![cmd](https://user-images.githubusercontent.com/58995691/142638975-7ddfaf81-005a-4499-ae72-3d67ee726e5a.jpg)
![taskManager](https://user-images.githubusercontent.com/58995691/142638979-f58fff90-0f17-47df-98c9-9a26374fe43f.jpg)

First everythings good, until i let it work for a while, and after 100 websites, or less it depends of the mood, i got this
![cmdError](https://user-images.githubusercontent.com/58995691/142639341-d3149d5a-1d5a-4880-bc8e-5cbdbe62cce8.jpg)

with a complete overcharge of task manager
![taskManagerChromeOverCharge2](https://user-images.githubusercontent.com/58995691/142639448-52c99710-250f-4f92-95ec-b8372687f7ad.jpg)
![taskManagerChromeOverCharge](https://user-images.githubusercontent.com/58995691/142639452-28b23795-d812-484b-a188-c55b5e41267c.jpg)


Again, this is a great tool with such rapidity of analyse!
Thank you so much

**Comment by Edu4rdSHL** [comment]
Thanks for the detailed issue, Max. It's a well-known problem of tools using Chromium-based browsers to take screenshots (sadly there is not a better alternative), Chrome-based browsers refuse to finish the process, even when the screenshot has been already taken, I have created a workaround for this [here](https://github.com/Findomain/Findomain/tree/master/Utilities) but only works on Linux, no idea about Windows. Anyways I will continue investigating and see if I can manage that directly inside Findomain.

**Comment by MaxArthurQueen** [comment]
:_) Ok, I understaind! Then maybe you could help with my needs: I loved the screenshot option because it only capture the websites with errors 404/403... I read the Help of Findomain, but because i'm a beginner in security, I couldn't be able to see if there is an option that would return a list of websites in a file.txt , but only those with the errors we seek for?

Thank you so much!!

**Comment by Edu4rdSHL** [comment]
What do you mean exactly "with the errors we seek for"? Did you mean text inside the HTML? Specific status codes?

**Comment by MaxArthurQueen** [comment]
I am seeking for 404 errors or status codes wich are compatibles with subdomain takerover

**Comment by Edu4rdSHL** [comment]
Hola, mira yo lo que te recomiendo es usar [Nuclei](https://github.com/projectdiscovery/nuclei) para revisar los takeovers, [aquí](https://twitter.com/pdnuclei/status/1260813090423050240) hay un ejemplo de como hacerlo. Si nuclei no llegara a cumplir las espectativas y te interesa una herramienta privada, puedes escribirme en [Twitter](https://twitter.com/edu4rdshl).

**Comment by MaxArthurQueen** [comment]
Bueno muchas gracias! Lo probaré mañana pero de todos modos te agradezco infinitamente!

**Comment by Edu4rdSHL** [comment]
After long research, it's definitely a problem with Chrome and not with us.
