### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by vansh1** [Findomain/Findomain#160]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/args.rs:115:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: IOT instruction  findomain --http-status -v -t theforage.com --config 
                                                                                                                                                             

i just ran this command  
findomain --http-status -v -t theforage.com --config /root/tools/findomain/config.toml

**Comment by Edu4rdSHL** [comment]
Looks like a problem with the config file, can you paste it here?

**Comment by vansh1** [comment]
# Findomain configuration file. The following listed values are all the possible values you can set at the moment.
# IF YOU ARE NOT USING ONE OF THEM PLEASE LEAVE THIS EMPTY OR DELETE IT FROM THE FILE

postgres_connection = "Your postgres connection URI here in the following format: postgresql://user:password@host:port/database"
discord_webhook = "Your Discord webhook URL here"
slack_webhook = "Your Slack webhook URL here"
telegrambot_token = "Your Telegram bot token here"
telegram_chat_id = "Your Telegram chat ID here"
spyse_token = ""
fb_token = "Your Facebook bearer tokens here, please use comma to separate if multiple are added."
virustotal_token =  ""
securitytrails_token = ""
certspotter_token = "Your CertSpotter bearer tokens here, please use comma to separate if multiple are added."
c99_api_key = "Your C99.nl API keys here, please use comma to separate if multiple are added."
threads = "Number of threads here"
rate_limit = "Number of seconds for the rate limit here"
http_timeout = "Value in seconds for the HTTP Status check of subdomains. Default 5."
dbpush_if_timeout = "Enable --mtimeout flag. Possible values: true, false"
no_monitor = "Enable --no-monitor flag. Possible values: true, false"
randomize = "Randomize the order of the targets instead of sorting them alphabetically"
user_agents_file = "Path to user agents file"
exclude_sources = "List of sources to exclude separated by comma"

**Comment by vansh1** [comment]
that's my config file sir

**Comment by Edu4rdSHL** [comment]
Comment the variables that you don't need or delete them as proposed in the file's header, that will fix your problem.
