### ISSUE TITLE
error: Found argument '--unlock' 

### ISSUE THREAD

**Issue by SoufElhabti** [Findomain/Findomain#162]
hello i ve been following this guide https://findomain.app/the-real-power-of-findomain/ but i got this issue : 
when running `  sudo monitoring /var/findomain/targets.txt ` 

`error: Found argument '--unlock' which wasn't expected, or isn't valid in this context`

**Comment by Edu4rdSHL** [comment]
Remove the `--unlock` flag, it was deprecated.
