### ISSUE TITLE
Update the example configuration files.

### ISSUE THREAD

**Issue by ZeroDot1** [Findomain/Findomain#164]
With the last update, there were changes of the arguments, but these are not yet included in the configuration examples.
https://github.com/Findomain/Findomain/tree/master/config_examples 
This should definitely be changed to avoid request if the configuration file does not work.

**Comment by ZeroDot1** [comment]
Example 

threads = "Number of threads here"
-->
lighweight-threads = "Number of threads here"

**Comment by ZeroDot1** [comment]
It is better to store everything that is possible directly in the configuration file. Because if you use Findomain more often it is not so great if you have to input everything completely new every time.

**Comment by Edu4rdSHL** [comment]
Fixed in https://github.com/Findomain/Findomain/commit/e3435db9b93d54a1764f1e8980996b44834b4c94 and https://github.com/Findomain/Findomain/commit/4c8110795edefb2882f0222b326881dfbc3cda6d
