### ISSUE TITLE
Add pfSense Support

### ISSUE THREAD

**Issue by ZeroDot1** [Findomain/Findomain#167]
I would like it very much if we could use Findomain with pfSense.
All should be manageable via the WebGui, and the results should be available as TXT file directly via the browser.
This makes it possible to automate the subdomain search very efficiently.
https://github.com/pfsense

**Comment by Edu4rdSHL** [comment]
Hello, thanks for the suggestion. However, I don't understand how Findomain is related to a firewall and I don't understand what do you mean by "the WebGui", please can you explain and give me more details?

**Comment by ZeroDot1** [comment]
I think it would be a good idea to run Findomain directly on a pfSense firewall.

And the control of Findomain could be done via the web interface.

This would have the advantage that you could search for subdomains from any place in the world using your own firewall.
And that would have the additional weffekt that you could work more energy efficient because the firewall is running constantly.

**Comment by Edu4rdSHL** [comment]
So, for the web interface, I do not need to do anything. And looking for the PfSense packages it seems to use FreeBSD-ports, Findomain [is already there!](https://github.com/pfsense/FreeBSD-ports/tree/devel/net/findomain).

**Comment by ZeroDot1** [comment]
Unfortunately there is no package Findomain which can be used directly in the firewall.

![Bildschirmfoto vom 2022-02-13 13-07-25](https://user-images.githubusercontent.com/28985171/153800396-f616eebc-1fa7-4ed3-abb4-3dddae0921cd.png)
