### ISSUE TITLE
Bug: Unwanted file copy when import_subdomains_from is used.

### ISSUE THREAD

**Issue by ZeroDot1** [Findomain/Findomain#178]
Since the last update, there is the problem that there are unwanted file copies when import_subdomains_from is used.

This means that the output file with the results becomes several gigabytes large and entries are written more times in the file.

The used settings:

`'/findomain/target/release/findomain' -c '/home/config.toml' --resolvers '/home/resolvers.txt' --external-subdomains -f '/home/URLsToScan_00.txt' -u '/home/URLsToScanDONE.txt'`

**Comment by ZeroDot1** [comment]
![Bildschirmfoto vom 2022-04-12 20-13-39](https://user-images.githubusercontent.com/28985171/163027052-fd913d1a-1af5-4c79-955e-23d50ac3cd3a.png)

**Comment by Edu4rdSHL** [comment]
Hello, @ZeroDot1 . Thank you for the detailed report, I will look into it. Just a question, is the tool appending the scan results to the file, right?

**Comment by ZeroDot1** [comment]
From me it is meant that all results are collected in one file.
But no copy of the results should be written into the file, each result should occur only once, that would be perfect.
It so that all results of all scans (also the results coming from other tools) are collected in one big file, this I have then stored in the configuration, to get all relevant results also in a scan.
And to not let Findomain run into the empty, if once again the Internet connection breaks.

**Comment by ZeroDot1** [comment]
* Here is a sample output.

```py

smtp1.stex.com
lb1.stex.com
www.altcoinbuilders.com
altcoinbuilders.com
wallet.altcoinbuilders.com
insight.auroracoin.eu
app.stex.com
trezorcoinexplorer.altcoinbuilders.com
oo.stex.com
www-dev.stex.com
ar.stex.com
help-pubdocs.stex.com
reports.stex.com
ru-pool.club
exchange.stex.com
mo.stex.com
socket.stex.com
bizcrm-mail.stex.com
socketv2.stex.com
auroracoin.eu
app-staging5.stex.com
mail2.stex.com
resources.stex.com
mo-test.stex.com
uni.stex.com
app-lb.stex.com
20.auroracoin.eu
test.stex.com
autodiscover.stex.com
socket-staging5.stex.com
app-coin-images.stex.com
email-static.stex.com
apidocs.stex.com
landing.stex.com
alfa.stex.com
pool.altcoinbuilders.com
mail.stex.com
jointer.stex.com
bitrapool.altcoinbuilders.com
www.auroracoin.eu
api3.stex.com
pool2.altcoinbuilders.com
lb2.stex.com
blockexplorer.auroracoin.eu
custody.stex.com
gigahashpool.com
help-test.stex.com
www.stex.com
api3-staging.stex.com
help.stex.com
socketv2-staging5.stex.com
api3-staging5.stex.com
webwallet.altcoinbuilders.com
coins-logos.stex.com
bitgrin.stex.com
mo-an.stex.com
www.alfa.stex.com
www.ru-pool.club
explorer.auroracoin.eu
stex.com

Job finished in 15 seconds.
>> 📁 Subdomains for gigahashpool.com were saved in: .//home/URLsToScanDONE.txt 😀

Good luck Hax0r 💀!

Rate limit set to 3 seconds, waiting to start next enumeration.

Target ==> greencoin.space

Getting amass subdomains for greencoin.space
Getting subfinder subdomains for greencoin.space
Searching in the Sublist3r API... 🔍
Searching in the Crtsh database API... 🔍
Searching in the Spyse API... 🔍
Searching in the Bufferover Free API... 🔍
Searching in the CertSpotter API... 🔍
Searching in the Facebook API... 🔍
Searching in the Virustotal API using apikey... 🔍
Searching in the Threatcrowd API... 🔍
Searching in the Urlscan.io API... 🔍
Searching in the Bufferover Paid API... 🔍
Searching in the AnubisDB API... 🔍
Searching in the C99 API... 🔍
Searching in the Threatminer API... 🔍
Searching in the Archive.org API... 🔍
Error getting amass subdomains for greencoin.space

Searching in the FullHunt API... 🔍



```

**Comment by Edu4rdSHL** [comment]
Thank you for the detailed report, @ZeroDot1! It has been fixed and the problem was explained in the previous commit.

**Comment by ZeroDot1** [comment]
Yes, now it works very well again, thanks again.
