### ISSUE TITLE
findomain compiled artifacts bug 

### ISSUE THREAD

**Issue by at-r00t** [Findomain/Findomain#179]
when trying to do : `findomain -o subs.example.txt -t example.com`
the output is : 
```
error: Found argument 'subs.example.txt' which wasn't expected, or isn't valid in this context

USAGE:
    findomain --output

For more information try --help
```

which means that the program reads the output file as an argument !!

**Comment by Edu4rdSHL** [comment]
`-o/--output` doesn't accept arguments, it's automatically generated. As the help says:

```
   -o, --output                 Write to an output file. The name of the output file will be the target string with TXT
                                 format.
```

If you want to use a specific output file, then use `-u/--unique-output`

```
   -u, --unique-output <unique-output>
            Write all the results for a target or a list of targets to a specified filename.
```

Summary:

Change your command to: `findomain -u subs.example.txt -t example.com`
