### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by Ayush765** [Findomain/Findomain#181]
cargo build --release
   Compiling openssl-sys v0.9.74
   Compiling sct v0.7.0
   Compiling parking_lot v0.11.2
   Compiling webpki v0.22.0
   Compiling crossbeam-epoch v0.9.8
   Compiling rand_pcg v0.1.2
   Compiling rand_chacha v0.1.1
   Compiling crypto-common v0.1.3
   Compiling block-buffer v0.10.2
   Compiling url v2.2.2
   Compiling url v1.7.2
   Compiling num-traits v0.1.43
   Compiling tokio-macros v1.8.0
   Compiling futures-macro v0.3.21
   Compiling serde_derive v1.0.137
error: failed to run custom build command for `openssl-sys v0.9.74`

Caused by:
  process didn't exit successfully: `/root/findomain/target/release/build/openssl-sys-b327bb4e56fbb0cb/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running "perl" "./Configure" "--prefix=/root/findomain/target/release/build/openssl-sys-cee86472d51155cf/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"
  Configuring OpenSSL version 1.1.1q (0x1010111fL) for linux-x86_64
  Using os-specific seed configuration
  Creating configdata.pm
  Creating Makefile

  **********************************************************************
  ***                                                                ***
  ***   OpenSSL has been successfully configured                     ***
  ***                                                                ***
  ***   If you encounter a problem while building, please open an    ***
  ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
  ***   and include the output from the following command:           ***
  ***                                                                ***
  ***       perl configdata.pm --dump                                ***
  ***                                                                ***
  ***   (If you are new to OpenSSL, you might want to consult the    ***
  ***   'Troubleshooting' section in the INSTALL file first)         ***
  ***                                                                ***
  **********************************************************************
  running "make" "depend"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.22.0+1.1.1q/src/lib.rs:488:39
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Edu4rdSHL** [comment]
Please read [Build for 32 bits or another platform:](https://github.com/Findomain/Findomain/blob/master/docs/INSTALLATION.md#build-for-32-bits-or-another-platform)

- **Note:** You need to have [rust](https://rust-lang.org/), [make](http://www.gnu.org/software/make) and [perl](https://www.perl.org/) installed in your system first.

You're missing `make`.
