### ISSUE TITLE
Secure connection via Tor

### ISSUE THREAD

**Issue by ZeroDot1** [Findomain/Findomain#182]
Add a way to allow requests via Tor and a way with a key that uses a new Tor identity every e.g. 20 requests.
This should make the search secure and provide unfiltered results.

**Comment by Edu4rdSHL** [comment]
Honestly, that is not part of the purpose of Findomain, other tools already exists for that purpose, for example [torsocks](https://gitweb.torproject.org/torsocks.git). Why not just use them?
