### ISSUE TITLE
Add -all flag to subfinder for more results please

### ISSUE THREAD

**Issue by obreinx** [Findomain/Findomain#185]
in subfinder add the flag -all to get all possible subs

**Comment by Edu4rdSHL** [comment]
What does that flag do exactly?

**Comment by obreinx** [comment]
extended the sources used in subfinder for passive enumeration

**Comment by obreinx** [comment]
can you tell me please  how i can edit it myself , I really need to .

**Comment by Edu4rdSHL** [comment]
There's the file that you need to modify https://github.com/Findomain/Findomain/blob/master/src/external_subs.rs#L68, please send a PR after you modify it if you want.

**Comment by ZeroDot1** [comment]
I have made a PR, I hope everything is correct.

**Comment by Edu4rdSHL** [comment]
Can you confirm the fix,  @obreinx ?
