### ISSUE TITLE
A error has occurred while querying the Crtsh database.

### ISSUE THREAD

**Issue by ZeroDot1** [Findomain/Findomain#187]
Hm, I think the service might be offline.

❌ A error has occurred while querying the Crtsh database. Error: db error: ERROR: could not connect to server "old"
DETAIL: could not connect to server: Connection refused
	Is the server running on host "bddccwsql.brad.dc.comodoca.net" (10.0.16.55) and accepting
	TCP/IP connections on port 5432?. Trying the API method...
Searching in the Crtsh API... 🔍

**Comment by Edu4rdSHL** [comment]
I do not understand what do you want to say exactly with that, Findomain already uses that API if the database is not available, that's why it says `Trying the API method...`

https://github.com/Findomain/Findomain/blob/896ee1b316fad35d56e905ea62f4d0602e833103/src/sources.rs#L362-L378
