### ISSUE TITLE
I am not able to build findomain properly 

### ISSUE THREAD

**Issue by yogendradevil** [Findomain/Findomain#191]
![image](https://user-images.githubusercontent.com/81254268/201852821-7c660a31-f160-4e43-8a29-5a8fbc5c6b62.png)

Compiling headless_chrome v0.9.0 (https://github.com/Edu4rdSHL/rust-headless-chrome#e1c7aa0e)
**error: could not compile `headless_chrome`**
warning: build failed, waiting for other jobs to finish...
error: build failed

getting this error again and again.

**Comment by Edu4rdSHL** [comment]
Hello, it looks like that your machines is going out of memory and thus killing the build process. If you see, it's terminating with `SIGKILL` which is a signal usually sent by OOM killers.

Anyway, I have made some changes, can you please pull them and try again?

**Comment by yogendradevil** [comment]
> Hello, it looks like that your machines is going out of memory and thus killing the build process. If you see, it's terminating with `SIGKILL` which is a signal usually sent by OOM killers.
> 
> Anyway, I have made some changes, can you please pull them and try again?

![image](https://user-images.githubusercontent.com/81254268/201907171-c8bba69a-2d62-4e54-bc5b-774139277cab.png)

It is working fine now
Thank You,
