### ISSUE TITLE
When a try to install findomain it giving me this error

### ISSUE THREAD

**Issue by RizwanSiDdiqu1** [Findomain/Findomain#219]
![image](https://user-images.githubusercontent.com/72160000/209457290-fec64c91-97ba-406c-990b-ea6f41c29ec6.png)

**Comment by Edu4rdSHL** [comment]
That usually happens because your machine run out of memory in the build process. Use one of our pre-built binaries.

**Comment by RizwanSiDdiqu1** [comment]
thanks
