### ISSUE TITLE
Seemingly random freezes

### ISSUE THREAD

**Issue by lschanner-tenchi** [Findomain/Findomain#270]
Has anyone else had the issue of the tool simply freezing for no apparent reason?

I'm calling the tool for a large number of domains in parallel, and a certain percentage of the calls just never finish (even after a full hour). Could it be that I'm getting rate-limited by one of the API's used? How can I test this?

Thanks in advance for the attention!

**Comment by lschanner-tenchi** [comment]
"findomain-linux -t {domain} -u subdomains.txt --external-subdomains"

**Comment by obreinx** [comment]
I am having this same issue too , after enumerating a list of subdomains the tool suddenly freeze

**Comment by Edu4rdSHL** [comment]
I need the information I asked before to know what's going on.

- which exact command are you running.
- when the tool 'freeze', which processes are running on the computer.
- system logs.
