### ISSUE TITLE
Config file throws an error

### ISSUE THREAD

**Issue by shinigam9** [Findomain/Findomain#299]
When I try to run the findomain command with the config file option, it throws me below error.

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Empty }', src/args.rs:151:18

I tried commenting out whole config file and then it worked.

**Comment by Edu4rdSHL** [comment]
Hello, please comment out the options that you are not going to use and just leave the others enabled. The issue is that you're enabling an option that requires an integer (number) and leaving it empty.
