### ISSUE TITLE
Thread Failure

### ISSUE THREAD

**Issue by rain0x06** [Findomain/Findomain#300]
Leaves error:

thread 'tokio-runtime-worker' panicked at 'Failed to clone https future', C:\Users\runneradmin\.cargo\git\checkouts\fhc-995266df2515fefe\c6ea4c6\src\httplib.rs:54:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

when attempting to use a large import of subdomains

**Comment by Edu4rdSHL** [comment]
Define "a large import of subdomains" and also provide the exact command that you're using.
