### ISSUE TITLE
Release for Apple Silicon (arm64)

### ISSUE THREAD

**Issue by roger-dodger** [Findomain/Findomain#301]
Thanks a lot for providing this tool to the community - much appreciated.

Do you have any plans to also release a version that is built for Apple Silicon platform (arm64)?
If not, would you accept a pull request to extend the build pipeline for it?

Thanks and regards,
Roger

**Comment by Edu4rdSHL** [comment]
Hello, thank you for your feedback. I would love to see a PR for supporting Apple Silicon.

Thank you.

**Comment by roger-dodger** [comment]
Hi Eduard,

glad to hear that you are open for PRs.

I just created two of them;
- #302 to extend the make-release workflow to build both, a binary for macOS on Intel, and macOS with Apple Silicon platform
- #303 a new workflow to build and push multiplatform Docker images. With this, the images should support Linux with amd64 architecture but also Docker on macOS with either amd64 or arm64 architecture.

Looking forward to get your feedback.

Best regards,
Roger

**Comment by Edu4rdSHL** [comment]
Hi, Roger. Thank you for all the work, [Findomain 9.0.1](https://github.com/Findomain/Findomain/releases/tag/9.0.1) is out and does contain the Apple Silicon asset. Marking this issue as complete.
