### ISSUE TITLE
Feature Request: -silent mode to only output found subdomains.

### ISSUE THREAD

**Issue by gprime31** [Findomain/Findomain#309]
tool is great but needs a flag to get rid of  the screen full of ---> No subdomains were found for the target:
besides >/dev/null 2>&1

**Comment by Edu4rdSHL** [comment]
Hi, now `-q/--quiet` doesn't print any informational messages.

**Comment by gprime31** [comment]
> Hi, now `-q/--quiet` doesn't print any informational messages.

Awesome, thanks!!!
