### ISSUE TITLE
findomain-linux 9.0.2 release still contains version 9.0.1

### ISSUE THREAD

**Issue by leorac** [Findomain/Findomain#312]
How to reproduce

```
$ wget https://github.com/Findomain/Findomain/releases/download/9.0.2/findomain-linux.zip
$ unzip findomain-linux.zip
$ chmod +x findomain
$ ./findomain --version

Findomain 9.0.1
```

**Comment by riramar** [comment]
Same here.

**Comment by Edu4rdSHL** [comment]
Hello, thanks for the report. I forgot to update the version metadata, but the features are there. It has been fixed in https://github.com/Findomain/Findomain/commit/7477a248b6c3a2407de992d6ba2740cb73030edf, new release coming.
