### ISSUE TITLE
amass external subdomain not working anymore

### ISSUE THREAD

**Issue by kaetir** [Findomain/Findomain#321]
According to [this comment](https://github.com/owasp-amass/amass/issues/811#issuecomment-1107688322), the `-nolocaldb` flag is no longer supported. Which break the --external-subdomains option. 

This can be confirmed by trying the [line present in the external_subs.rs](https://github.com/Findomain/Findomain/blob/7477a248b6c3a2407de992d6ba2740cb73030edf/src/external_subs.rs#L28) manually. 
```bash
amass enum -passive -nolocaldb -d example.com -o amass_out
flag provided but not defined: -nolocald
```

The flag has been deleted in [this commit](https://github.com/owasp-amass/amass/commit/69d4a5ae6efd20acd4e6610105d45fc19dc773d4)

**Comment by Edu4rdSHL** [comment]
Hello, thanks for the report, it should be fixed now.
