### ISSUE TITLE
Telegram webhook option not working

### ISSUE THREAD

**Issue by fuomag9** [Findomain/Findomain#324]
As per title, the telegram webhook option does not work:

`efeff19f4ebb# findomain_telegrambot_token="token" findomain_telegrambot_chat_id="chatid" findomain -m -t example.com --postgres-database findomain --postgres-user findomain --postgres-password findomain --postgres-host postgres --postgres-port 5432`                    
```
Testing connection to database server...
Connection to database server successful, performing enumeration!

Target ==> example.com

You must provide a webhook to use the monitoring API.
```

**Comment by Edu4rdSHL** [comment]
Hello, @fuomag9. Thank you for reporting it, the issue was in the documentation, you just need to change `findomain_telegrambot_chat_id` to `findomain_telegram_chat_id` and it will works.
